from app.models import db, Drink_ingredient

def seed_drink_ingredients():
  drinkIngredients = [
    Drink_ingredient(drinkId=1, ingredientId=72),
    Drink_ingredient(drinkId=1, ingredientId=20),
    Drink_ingredient(drinkId=1, ingredientId=429),
    Drink_ingredient(drinkId=1, ingredientId=462),
    Drink_ingredient(drinkId=2, ingredientId=271),
    Drink_ingredient(drinkId=2, ingredientId=274),
    Drink_ingredient(drinkId=2, ingredientId=429),
    Drink_ingredient(drinkId=2, ingredientId=304),
    Drink_ingredient(drinkId=2, ingredientId=411),
    Drink_ingredient(drinkId=3, ingredientId=203),
    Drink_ingredient(drinkId=3, ingredientId=171),
    Drink_ingredient(drinkId=3, ingredientId=309),
    Drink_ingredient(drinkId=4, ingredientId=271),
    Drink_ingredient(drinkId=4, ingredientId=274),
    Drink_ingredient(drinkId=4, ingredientId=365),
    Drink_ingredient(drinkId=5, ingredientId=7),
    Drink_ingredient(drinkId=5, ingredientId=275),
    Drink_ingredient(drinkId=5, ingredientId=129),
    Drink_ingredient(drinkId=5, ingredientId=138),
    Drink_ingredient(drinkId=6, ingredientId=429),
    Drink_ingredient(drinkId=6, ingredientId=274),
    Drink_ingredient(drinkId=6, ingredientId=77),
    Drink_ingredient(drinkId=7, ingredientId=127),
    Drink_ingredient(drinkId=7, ingredientId=270),
    Drink_ingredient(drinkId=8, ingredientId=271),
    Drink_ingredient(drinkId=8, ingredientId=122),
    Drink_ingredient(drinkId=8, ingredientId=352),
    Drink_ingredient(drinkId=9, ingredientId=203),
    Drink_ingredient(drinkId=9, ingredientId=79),
    Drink_ingredient(drinkId=9, ingredientId=435),
    Drink_ingredient(drinkId=10, ingredientId=203),
    Drink_ingredient(drinkId=10, ingredientId=263),
    Drink_ingredient(drinkId=10, ingredientId=430),
    Drink_ingredient(drinkId=10, ingredientId=151),
    Drink_ingredient(drinkId=11, ingredientId=442),
    Drink_ingredient(drinkId=11, ingredientId=449),
    Drink_ingredient(drinkId=11, ingredientId=275),
    Drink_ingredient(drinkId=11, ingredientId=398),
    Drink_ingredient(drinkId=12, ingredientId=163),
    Drink_ingredient(drinkId=12, ingredientId=206),
    Drink_ingredient(drinkId=13, ingredientId=163),
    Drink_ingredient(drinkId=13, ingredientId=274),
    Drink_ingredient(drinkId=13, ingredientId=116),
    Drink_ingredient(drinkId=13, ingredientId=241),
    Drink_ingredient(drinkId=14, ingredientId=383),
    Drink_ingredient(drinkId=14, ingredientId=429),
    Drink_ingredient(drinkId=14, ingredientId=349),
    Drink_ingredient(drinkId=14, ingredientId=462),
    Drink_ingredient(drinkId=14, ingredientId=72),
    Drink_ingredient(drinkId=14, ingredientId=264),
    Drink_ingredient(drinkId=15, ingredientId=461),
    Drink_ingredient(drinkId=15, ingredientId=447),
    Drink_ingredient(drinkId=15, ingredientId=263),
    Drink_ingredient(drinkId=15, ingredientId=480),
    Drink_ingredient(drinkId=15, ingredientId=437),
    Drink_ingredient(drinkId=15, ingredientId=274),
    Drink_ingredient(drinkId=16, ingredientId=435),
    Drink_ingredient(drinkId=16, ingredientId=72),
    Drink_ingredient(drinkId=16, ingredientId=20),
    Drink_ingredient(drinkId=16, ingredientId=241),
    Drink_ingredient(drinkId=16, ingredientId=287),
    Drink_ingredient(drinkId=16, ingredientId=317),
    Drink_ingredient(drinkId=17, ingredientId=461),
    Drink_ingredient(drinkId=17, ingredientId=442),
    Drink_ingredient(drinkId=17, ingredientId=271),
    Drink_ingredient(drinkId=17, ingredientId=203),
    Drink_ingredient(drinkId=17, ingredientId=116),
    Drink_ingredient(drinkId=17, ingredientId=264),
    Drink_ingredient(drinkId=18, ingredientId=271),
    Drink_ingredient(drinkId=18, ingredientId=325),
    Drink_ingredient(drinkId=18, ingredientId=449),
    Drink_ingredient(drinkId=18, ingredientId=436),
    Drink_ingredient(drinkId=18, ingredientId=95),
    Drink_ingredient(drinkId=19, ingredientId=17),
    Drink_ingredient(drinkId=19, ingredientId=413),
    Drink_ingredient(drinkId=20, ingredientId=36),
    Drink_ingredient(drinkId=20, ingredientId=224),
    Drink_ingredient(drinkId=20, ingredientId=203),
    Drink_ingredient(drinkId=20, ingredientId=436),
    Drink_ingredient(drinkId=20, ingredientId=86),
    Drink_ingredient(drinkId=20, ingredientId=95),

  ]

# Drink_ingredient(drinkId=, ingredientId=),

  db.session.add_all(drinkIngredients)

  db.session.commit()

def undo_drink_ingredients():
  db.session.execute('TRUNCATE drink_ingredients RESTART IDENTITY CASCADE')
  db.session.commit()
